### ISSUE TITLE
vaMaxNumDisplayAttributes() returns wrong value when driver not implemented API

### ISSUE THREAD

**Issue by sureshg20** [intel/libva-utils#229]
Result of this , we are seeing failures in

[  FAILED  ] VAAPIDisplayAttribs.QueryDisplayAttribs
[  FAILED  ] VAAPIDisplayAttribs.GetDisplayAttribs
[  FAILED  ] VAAPIDisplayAttribs.SetDisplayAttribs
Failed 3 tests are due to "vaMaxNumDisplayAttributes". On driver side these apis are not implemented and returned with no_attributes as zero, but still tests shows failed

Please refer :https://chromium.googlesource.com/chromium/deps/mesa/+/master/src/gallium/state_trackers/va/va_display.c

**Comment by yellowdoge** [comment]
@sreerenjb @xhaihao can you guys take a look at this request please?

**Comment by sushma08** [comment]
@XinfengZhang can you please help here? Thank you.

**Comment by XinfengZhang** [comment]
from the code: https://chromium.googlesource.com/chromium/deps/mesa/+/refs/heads/main/src/gallium/state_trackers/va/va_display.c#39
if (!(attr_list && num_attributes))
   return VA_STATUS_ERROR_UNKNOWN;

but from the test code: https://github.com/intel/libva-utils/blob/master/test/test_va_api_display_attribs.cpp#L98-L102
            vaQueryDisplayAttributes(m_vaDisplay, NULL, &numAttribs));

        EXPECT_TRUE(
            status == VaapiStatus(VA_STATUS_SUCCESS) or
            status == VaapiStatus(VA_STATUS_ERROR_UNIMPLEMENTED));

the parameter is null, and expectation is success or unimplemented.

**Comment by uartie** [comment]
Agree with @XinfengZhang.  It does not make sense for the driver to validate the `attr_list` pointer, etc. if the driver is not planning to use it.  Just remove the check in the driver and the remaining logic should be acceptable.

**Comment by uartie** [comment]
> Agree with @XinfengZhang. It does not make sense for the driver to validate the `attr_list` pointer, etc. if the driver is not planning to use it. Just remove the check in the driver and the remaining logic should be acceptable.

Wait, `num_attributes` is the only pointer that is used by the driver's query _implementation_... so it needs to be checked (unfortunately, the libva-utils test suite is not testing that use-case).  IMO, it's easier if the driver just returns unimplemented immediately since that's the intention based on your bug description.

Not sure why you're seeing Get/Set test failures (based on the latest driver code that @XinfengZhang linked above).

Nonetheless, I would categorize this as a driver bug, not a libva-utils bug.
