### ISSUE TITLE
unit test overhad from initialization

### ISSUE THREAD

**Issue by anholt** [intel/libva-utils#247]
I'm working on enabling libva unit testing in Mesa so we can keep the radeonsi VA driver regression free.  For our lower-powered hardware, even with gtest sharded across 4 cores (https://gitlab.freedesktop.org/anholt/deqp-runner/-/merge_requests/24), we're looking at about 25 minutes to complete the test suite, which won't be within our CI time budget.

Looking at the profile on my desktop radeonsi system, 41% of CPU time is spent in `__vaDriverInit_1_13` and its children  If the unit tests (at least some of them?) could share driver setup (see https://github.com/google/googletest/blob/master/docs/advanced.md#sharing-resources-between-tests-in-the-same-test-suite), that could save us a ton of time in testing and let us run the full testsuite pre-merge.

**Comment by XinfengZhang** [comment]
not sure whether your issue was fixed after https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/13324. I just have a quick try on my Intel skl platform 
 it just need <1 mins:
[       OK ] QueryConfig/VAAPIQueryConfig.CheckEntrypointsForProfile/22 (2 ms)
[----------] 23 tests from QueryConfig/VAAPIQueryConfig (39 ms total)

[----------] Global test environment tear-down
[==========] 17415 tests from 14 test cases ran. (34459 ms total)
[  PASSED  ] 17415 tests.
